// City data for Azerbaijan
export const AZERBAIJAN_CITIES = {
  main: [
    "Bakı",
    "Sumqayıt",
    "Xırdalan",
    "Gəncə",
    "Qəbələ",
    "Quba",
    "Xaçmaz",
    "Lənkəran",
    "Mingəçevir",
    "Şəki",
    "Qusar",
    "Şirvan",
  ],
  other: [
    "Ağcabədi",
    "Ağdam",
    "Ağdaş",
    "Ağdərə",
    "Ağstafa",
    "Ağsu",
    "Astara",
    "Balakən",
    "Beyləqan",
    "Bərdə",
    "Biləsuvar",
    "Cəbrayıl",
    "Cəlilabad",
    "Culfa",
    "Daşkəsən",
    "Füzuli",
    "Gədəbəy",
    "Goranboy",
    "Göyçay",
    "Göygöl",
    "Göytəpə",
    "Hacıqabul",
    "Horadiz",
    "İmişli",
    "İsmayıllı",
    "Kəlbəcər",
    "Kürdəmir",
    "Laçın",
    "Lerik",
    "Masallı",
    "Nabran",
    "Naftalan",
    "Naxçıvan",
    "Neftçala",
    "Oğuz",
    "Ordubad",
    "Qax",
    "Qazax",
    "Qobustan",
    "Qubadlı",
    "Saatlı",
    "Sabirabad",
    "Şabran",
    "Şahbuz",
    "Salyan",
    "Şamaxı",
    "Samux",
    "Şəmkir",
    "Şərur",
    "Siyəzən",
    "Şuşa",
    "Tərtər",
    "Tovuz",
    "Ucar",
    "Xankəndi",
    "Xızı",
    "Xocalı",
    "Xocavənd",
    "Xudat",
    "Yardımlı",
    "Yevlax",
    "Zaqatala",
    "Zəngilan",
    "Zərdab",
  ],
} as const;

// Helper function to get all cities in a flat array
export const getAllCities = () => [
  ...AZERBAIJAN_CITIES.main,
  ...AZERBAIJAN_CITIES.other,
];

// Helper function to get main cities only
export const getMainCities = () => AZERBAIJAN_CITIES.main;

// Helper function to get other cities only
export const getOtherCities = () => AZERBAIJAN_CITIES.other;
